### ISSUE TITLE
Ajour compatibility

### ISSUE THREAD

**Issue by SkywardShadow** [GurliGebis/AngrierWorldQuests#10]
It would be nice to not be reliant on Curseforge for releases. I'm working to change my addon sources to Github using Ajour. If/when Overwolf disables the ability for other tools to pull from Curseforge, we'll be able to continue without them.

While writing this and looking at the other Github, I see that the author is the same, and that other ticket is closed. I hope you'll reconsider for this release!

Thank you.

**Comment by GurliGebis** [comment]
Since it is broken in Ajour, and Curseforge still allows downloads from other clients, I don't see the need for it right now.

**Comment by GurliGebis** [comment]
Closing for now - if Curseforge becomes a problem, I'll take it up again :)
