### ISSUE TITLE
Move world quests tab below campaign tabs

### ISSUE THREAD

**Issue by addonaddict** [GurliGebis/AngrierWorldQuests#11]
Simple, when user selected show at top, can we have it below the campaign window?
Seems more visually appealing
Perhaps a toggle if others want it differently?
Thanks for maintaining :) love the addon

example:
![image](https://user-images.githubusercontent.com/73442541/103179961-1d8ffa00-485f-11eb-8a33-89e754fc0b45.png)

**Comment by cybern4ut** [comment]
I've had the same issue and no matter how much some users say they like World Quest Tab, to me nothing beat this addon. I find everything clearer and would really like if you could fix the positioning. Thank you for this!

**Comment by cybern4ut** [comment]
> 
> 
> Simple, when user selected show at top, can we have it below the campaign window?
> Seems more visually appealing
> Perhaps a toggle if others want it differently?
> Thanks for maintaining :) love the addon
> 
> example:
> ![image](https://user-images.githubusercontent.com/73442541/103179961-1d8ffa00-485f-11eb-8a33-89e754fc0b45.png)

Hi there addonaddict, this a a problem but with /awq you can uncheck display at the top of the quest log but it's still not in the right place though it will be at the bottom of all the other quests you have but it's better than nothing for now.

**Comment by addonaddict** [comment]
Yes thanks, thats how i have it now
I was just wondering if u could revert the top position to BFA and before functionality where it was below the campaign

by the way your screenshot shows the old functionality that doesnt work in shadowlands zones

thanks

**Comment by cybern4ut** [comment]
No that screenshot is from the original addon released by Ermads I was just pointing the fact that's where we want it under campaign me and you both. Hopefully, Gurligebis will be able to help us out. I couldn't figure out the code to put it under campaign. It would also be nice to implement, map pins icons like BetterWorldQuests as an option.

Cheers!

**Comment by addonaddict** [comment]
Oh my bad sorry

**Comment by GurliGebis** [comment]
Hey,

I finally had time to get world quests unlock for Shadowlands.
I'm seeing the same problem, and think I have found the position in the code where the problem is happening (still pretty new to the codebase after taking it over).

I'll see what I can do to fix it :)

**Comment by addonaddict** [comment]
no worries take your time, thanks!

**Comment by GurliGebis** [comment]
Sorry for taking so long to fix this.
Version 0.32.0 has been released, which fixes the problem.

**Comment by GurliGebis** [comment]
Make that 0.32.1 , I made a mistake with 0.32.0, causing it to fail most of the time, just not for my exact list of quests :)
