### ISSUE TITLE
Not working with Better World Quests

### ISSUE THREAD

**Issue by griddark** [GurliGebis/AngrierWorldQuests#12]
**Describe the bug**
Map becoming buggy when installed with Better World Quests, icons showing in places they're not supposed to, and other addons (handynotes) also start showing icons where they shouldn't. Turning the addon off all the errors go away. 

**How to reproduce**
Run Better World Quests along side your addon. 

**What did you expect?**
Map pins to work.

**Screenshots**
![Map](https://i.imgur.com/NZUGlgS.png "Example")

<details>
<summary>**Bugsack** Click to expand!</summary>
31x ...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:319: attempt to index local 'tagInfo' (a nil value)
[string "@Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua"]:319: in function `AddWorldQuest'
[string "@BetterWorldQuests\PinProvider.lua"]:107: in function `RefreshAllData'
[string "@Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:76: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:559: in function <...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:557>
[string "=[C]"]: ?
[string "=[C]"]: in function `OnMapChanged'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:234: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:59: in function `SetMapID'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:757: in function `NavigateToParentMap'
[string "@Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:127: in function <...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:102>
[string "=[C]"]: ?

Locals:
self = <table> {
 OnClearFocusedQuestID = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:79
 EvaluateCheckBounties = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:63
 OnEvent = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:166
 OnMapInsetMouseLeave = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:46
 AddWorldQuest = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:308
 SetUsesSpellEffect = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:15
 SetMatchWorldMapFilters = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:3
 OnCanvasScaleChanged = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:50
 registeredEvents = <table> {
 }
 PingQuestID = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:153
 owningMap = WorldMapFrame {
 }
 OnSetFocusedQuestID = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:75
 activePins = <table> {
 }
 OnHide = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:184
 ShouldShowQuest = <function> defined @AngrierWorldQuests\QuestFrame.lua:1033
 IsUsingSpellEffect = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:23
 OnCanvasSizeChanged = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:58
 markActiveQuests = true
 checkBounties = true
 usesSpellEffect = true
 matchWorldMapFilters = true
 IsMarkingActiveQuests = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:98
 OnRemoved = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:120
 OnAdded = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:102
 OnMapChanged = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:74
 OnSuperTrackingChanged = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:255
 GetMap = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:70
 ClearFocusedQuestID = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:134
 SignalEvent = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:97
 GetPinTemplate = <function> defined @BetterWorldQuests\PinProvider.lua:58
 IsMatchingWorldMapFilters = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:11
 OnShow = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:177
 HandleMouseAction = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:103
 spellEffectPin = <unnamed> {
 }
 suppressedQuests = <table> {
 }
 OnMapInsetSizeChanged = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:38
 IsCheckingBounties = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:59
 IsQuestSuppressed = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:381
 SetCheckBounties = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:50
 ShouldOverrideShowQuest = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:196
 GetBountyQuestID = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:149
 ticker = <table> {
 }
 SetBountyQuestID = <function> defined @Blizzard_SharedMapDataProviders\WorldQues</details>

**Comment by GurliGebis** [comment]
Looking at the bugsack, it seems like the problem is in the code for the Better World Quests addon.

More specifically this line:
BetterWorldQuests\PinProvider.lua"]:107: in function `RefreshAllData'

So it is not something I can change in here - please try and contact the people making the BetterWorldQuests addon, and see if they can see what i causing it on their end.

**Comment by griddark** [comment]
Thanks for taking the time GurliGebis to address this, the author of Better World Quests addon pointed out it was his addon and he had no intention of changing it, so I just had to find an alternative, as his addon interferes with any other world quest addon.
