### ISSUE TITLE
Not showing up in CurseForge App

### ISSUE THREAD

**Issue by kittykatmax** [GurliGebis/AngrierWorldQuests#14]
Perhaps this is deliberate, but I can do a search for "angrier" or "world quests" and your fork does not show up.  I actually saw your fork (thank you!!!) by accident.

Thank you for keeping this addon alive!

**Comment by Gnarfoz** [comment]
![image](https://user-images.githubusercontent.com/65654/106640946-f37cd680-6586-11eb-8ae9-a67aabba2760.png)
Seems to work here.

**Comment by GurliGebis** [comment]
It is showing up on my machine - it is most likely a caching issue.
Is it still not showing up on your machine?

**Comment by GurliGebis** [comment]
I'm closing for now, please let me know if it still won't show up.
