### ISSUE TITLE
9.1 Error

### ISSUE THREAD

**Issue by MetalHeadSeven** [GurliGebis/AngrierWorldQuests#18]
2x AngrierWorldQuests\QuestFrame.lua:262: Usage: GameTooltip:SetText("text" [, color, wrap])
[string "=[C]"]: in function `SetText'
[string "@AngrierWorldQuests\QuestFrame.lua"]:262: in function <AngrierWorldQuests\QuestFrame.lua:233>

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 SetExistingSocketGem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 RightEdge = <unnamed> {
 }
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 SetSocketGem = <function> defined =[C]:-1
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 Show = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 numMoneyFrames = 1
 SetBuybackItem = <function> defined =[C]:-1
 SetWeeklyReward = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 TopRightCorner = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 sf = <unnamed> {
 }
 ftype = "u"
 SetBagItem = <function> defined =[C]:-1
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 textLeft1Font = "GameTooltipHeaderText"
 SetGuildBankItem = <function> defined =[C]:-1
 updateTooltipTimer = 0.151000
 TopLeftCorner = <unnamed> {
 }
 Hide = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 ClearLines = <function> defined =[C]:-1
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 hasMoney = 1
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @Postal\Libs\AceHook-3.0\AceHook-3.0.lua:100
 GetBackdrop = <function> defined @Postal\Libs\AceHook-3.0\AceHook-3.0.lua:100
 SetHeirloomByItemID = <function> defined =[C]:-1
 comparing = false
 SetQuestItem = <function> defined =[C]:-1
 waitingForData = false
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
 SetTrainerService = <function> defined =[C]:-1
 BottomLeftCorner = <unnamed> {
 }
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @Postal\Libs\AceHook-3.0\AceHook-3.0.lua:100
 shoppingTooltips = <table> {
 }
 TextRight1 = GameTooltipTextRight1 {
 }
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 Center = <unnamed> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 SetTradeTargetItem = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 BottomEdge = <unnamed> {
 }
 SetQuestLogItem = <function> defined =[C]:-1
 textLeft2Font = "GameTooltipText"
 ItemTooltip = <unnamed> {
 }
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 ApplyBackdrop = <function> defined @FrameXML\UIParent.lua:5575
 SetItemByID = <function> defined =[C]:-1
 backdropInfo = <table> {
 }
 SetItemKey = <function> defined =[C]:-1
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:299
 TextLeft1 = GameTooltipTextLeft1 {
 }
 BottomOverlay = <unnamed> {
 }
 SetRecipeResultItem = <function> defined =[C]:-1
}
(*temporary) = nil
#

**Comment by GurliGebis** [comment]
I cannot reproduce the problem, but it looks like it is colliding with libraries in the Postal addon (which I'm also using).
Is your Postal addon updated to the newest version?

**Comment by MetalHeadSeven** [comment]
Thanks for the fast reply.  The latest update for Postal showed up after I reported this and it does seem to be fixed now.

**Comment by GurliGebis** [comment]
You're welcome 🙂
