### ISSUE TITLE
Error when hoving over sort-by-anima button.

### ISSUE THREAD

**Issue by Hitane** [GurliGebis/AngrierWorldQuests#19]
I get this error when hoving over the show anima world quests button in the quest list: 

> Message: Interface\AddOns\AngrierWorldQuests\QuestFrame.lua:262: Usage: GameTooltip:SetText("text" [, color, wrap])
Time: Wed Jun 30 16:50:28 2021
Count: 17
Stack: Interface\AddOns\AngrierWorldQuests\QuestFrame.lua:262: Usage: GameTooltip:SetText("text" [, color, wrap])
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetText'
[string "@Interface\AddOns\AngrierWorldQuests\QuestFrame.lua"]:262: in function <Interface\AddOns\AngrierWorldQuests\QuestFrame.lua:233>
Locals: errMsg = "Interface\AddOns\AngrierWorldQuests\QuestFrame.lua:262: Usage: GameTooltip:SetText("text" [, color, wrap])"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

![image](https://user-images.githubusercontent.com/4742222/124036405-8fd6c800-d9c3-11eb-9420-7fd34f047620.png)

**Comment by GurliGebis** [comment]
This has been fixed in #20 , please update to version 0.34.1 and see if that fixes the problem.
