### ISSUE TITLE
LUA Errors in fated raids

### ISSUE THREAD

**Issue by karpana** [GurliGebis/AngrierWorldQuests#22]
Had to figure out how to enable the taint log to figure out that Angrier World Quests has been the root cause for this funny "taint" problem...

in the taint log I see messages such as these
`An action was blocked in combat because of taint from AngrierWorldQuests - CompactRaidFrame10:Hide()
    Interface\FrameXML\CompactUnitFrame.lua:381 CompactUnitFrame_UpdateVisible()
    Interface\FrameXML\CompactUnitFrame.lua:309 CompactUnitFrame_UpdateAll()
    Interface\FrameXML\CompacUnitFrame.lua:193
`

**Comment by karpana** [comment]
likely also important, it is being generated on number of CompactRaidFrames ... 1 thru 31

**Comment by GurliGebis** [comment]
That error is not an error in the addon.
Have a look here: https://authors.curseforge.com/forums/world-of-warcraft/official-addon-threads/unit-frames/221379-an-action-was-blocked-in-combat-because-of-taint
