### ISSUE TITLE
just sharing an error

### ISSUE THREAD

**Issue by klepp0906** [GurliGebis/AngrierWorldQuests#24]
first off, huge thank you for continuing this addon.  so many addons nowadays are bloatfests.  this is the most concise simple world quest addon ive found.  its been all but perfect for my use.   

> 1x [ADDON_ACTION_FORBIDDEN] AddOn 'AngrierWorldQuests' tried to call the protected function 'UseAction()'.
> [string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
> [string "=[C]"]: in function `UseAction'
> [string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
> [string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
> [string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
> [string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
> [string "@Interface/FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
> [string "@Interface/FrameXML/MultiActionBars.lua"]:14: in function `MultiActionButtonDown'
> [string "MULTIACTIONBAR1BUTTON10"]:2: in function <[string "MULTIACTIONBAR1BUTTON10"]:1>

**Comment by GurliGebis** [comment]
The issue is not related to this addon.
Something else is tainting the UI, which causes those errors.
With 10.0.2, Blizzard has locked things quiet alot down, which causes errors like this.

If one addon touches something, and taints it, it can break other stuff, when they try to use it, causing them to report errors like this, even though they are not the source of it.

**Comment by klepp0906** [comment]
gotcha, i appreciate the info.  will have to see if i can suss out what it is then.

**Comment by GurliGebis** [comment]
> gotcha, i appreciate the info. will have to see if i can suss out what it is then.

If you can find a way to reproduce it, you can try and disable some addons and see if the problem goes away, to narrow in on which one is causing it.
When you find one, try disabling everything else than it, and see if it still breaks.
